steps:
  - block: "Release"
    label: "Step 1"
    prompt: "Fill out the details for release"
    fields:
      - text: "Release Name"
        key: "release-name" 
      - text: "Release Notes"
        key: "release-notes"
      - text: "Release Version"
        hint: "What's the code name for this release? :name_badge:"
        required: false
        key: "release-version"
  - command: "echo $(buildkite-agent meta-data get release-name)"
    label: "Step 2"        
  - input: "Information please - 2"
    label: "Step 3"
    fields:
      - text: "What is the date today again?"
        key: "todays-date-2"
  - wait
  - command: "echo $(buildkite-agent meta-data get todays-date-2)"
    label: "Step 4"
